markdown: kramdown
safe: true
lsi: false
pygments: true
name: "RORLab Podcast"
description: "RORLab podcast, 루비온레일스를 다루며 격주로 진행되는 발표영상을 제공합니다."
url: http://rorlabpodcasts.github.io/
rorlab_url: http://rorlab.org/
sns: 
  twitter: https://twitter.com/rorlab
  facebook: https://www.facebook.com/groups/rubyonrailskorea
podcast:
  feed_url: http://rorlabpodcasts.github.io/podcast.xml
  copyright: 2013 RORLab
  author: "RORLab"
  keyword: "레일스,팟캐스트,루비,웹개발,웹,podcast,tech,rorlab,ruby,rails,ror,web,design"
  subtitle: "RORLab, Ruby On Rails 팟캐스트"
  owner_name: ChangHoon Jeong
  owner_email: iamseapy@gmail.com
  description: "RORLab에서는 Ruby On Rails를 처음 접하는 분들을 위해 Ruby On Rails 가이드 내용을 주로 다루며 격주로 모임을 가지고 있습니다. 모임때마다 생성되는 동영상 자료는 팟캐스트로 제공됩니다. RORLab에 대한 자세한 정보는 웹페이지 http://rorlab.org 를 참고하시기 바랍니다. 제35회 RORLab 부터는 NAVER의 지원을 받아 개최됩니다. http://developer.naver.com/wiki/pages/Community"
  image: http://rorlabpodcasts.github.io/images/rorlab-logo-no-corner-1400.jpg
naver_d2:
  image: http://rorlabpodcasts.github.io/images/naver_d2_banner_164.png
  url: http://developer.naver.com/wiki/pages/Community